### ISSUE TITLE
Typo on Demo Terminal App

### ISSUE THREAD

**Issue by yidakee** [graft-project/exchange-broker#3]
Reads Etherium where it should read Ethereum;

<img width="1272" alt="screenshot 2019-01-26 at 22 03 46" src="https://user-images.githubusercontent.com/16577836/51793932-42d1e480-21c0-11e9-97e5-58bf3332ab85.png">

**Comment by Dju01** [comment]
> Reads Etherium where it should read Ethereum;
> 
> <img alt="screenshot 2019-01-26 at 22 03 46" width="1272" src="https://user-images.githubusercontent.com/16577836/51793932-42d1e480-21c0-11e9-97e5-58bf3332ab85.png">

Fixed, you can check.
